# Generated by Django 4.2.17 on 2026-03-08 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cuisine_type', models.CharField(choices=[('local', 'Local Cuisine'), ('chinese', 'Chinese'), ('malay', 'Malay'), ('indian', 'Indian'), ('peranakan', 'Peranakan'), ('seafood', 'Seafood'), ('street_food', 'Street Food'), ('hawker', 'Hawker'), ('fine_dining', 'Fine Dining'), ('cafe', 'Café & Coffee'), ('bakery', 'Bakery & Desserts'), ('vegetarian', 'Vegetarian/Vegan'), ('fusion', 'Fusion'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('western', 'Western'), ('other', 'Other')], max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri: 9am-9pm')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vendors/covers/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_profiles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendors/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'vendor_photos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
