# Generated by Django 4.2.17 on 2026-03-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food_tour', 'Food Tour'), ('cooking_class', 'Cooking Class'), ('tasting_menu', 'Tasting Menu'), ('street_food', 'Street Food Walk'), ('fine_dining', 'Fine Dining Experience'), ('market_tour', 'Market Tour'), ('cafe_hopping', 'Café Hopping'), ('workshop', 'Food Workshop'), ('festival', 'Food Festival'), ('other', 'Other')], default='food_tour', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='SGD', max_length=3)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('meeting_point', models.TextField(blank=True)),
                ('what_included', models.TextField(blank=True, help_text="What's included in the experience")),
                ('what_to_bring', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='experiences/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='experiences', to='experiences.tag')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='vendors.vendorprofile')),
            ],
            options={
                'db_table': 'food_experiences',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiences/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experiences.foodexperience')),
            ],
            options={
                'db_table': 'experience_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='foodexperience',
            index=models.Index(fields=['available_from'], name='food_experi_availab_2b5973_idx'),
        ),
        migrations.AddIndex(
            model_name='foodexperience',
            index=models.Index(fields=['category'], name='food_experi_categor_01bee6_idx'),
        ),
        migrations.AddIndex(
            model_name='foodexperience',
            index=models.Index(fields=['is_active'], name='food_experi_is_acti_97109b_idx'),
        ),
    ]
